# Generated by Django 5.0.8 on 2024-09-06 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='client',
            new_name='customer',
        ),
    ]
