# Generated by Django 5.0.8 on 2024-09-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_client_sale_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
