# Generated by Django 5.0.8 on 2024-09-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_sale_total_alter_saledetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
