# Generated by Django 5.0.8 on 2024-09-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_saledetail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('qr', 'QR'), ('cuenta_corriente', 'Cuenta Corriente')], default='efectivo', max_length=16),
        ),
    ]
