# Generated by Django 5.0.8 on 2024-09-23 12:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_customer_type_delete_customertype'),
        ('products', '0012_alter_product_name'),
        ('sales', '0012_alter_saledetail_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False if you want to deactivate this record.', verbose_name='active')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customers.customer')),
            ],
            options={
                'ordering': ['-created', '-modified', '-is_active'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False if you want to deactivate this record.', verbose_name='active')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.product')),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_details', to='sales.return')),
            ],
            options={
                'ordering': ['-created', '-modified', '-is_active'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
