# Generated by Django 5.0.8 on 2024-10-07 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_customer_type_delete_customertype'),
        ('sales', '0016_sale_needs_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='customers.customer'),
        ),
    ]
