# Generated by Django 5.0.8 on 2024-10-12 14:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_collect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
