# Generated by Django 5.0.8 on 2024-10-14 14:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_collect_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='applied_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
    ]
