# Generated by Django 5.0.8 on 2024-10-14 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_return_applied_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='applied_amount',
        ),
    ]
