# Generated by Django 5.0.8 on 2024-10-16 22:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_remove_return_reason_return_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
