# Generated by Django 5.0.8 on 2024-10-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_alter_statechange_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statechange',
            name='state',
            field=models.CharField(choices=[('creada', 'Creada'), ('pendiente_entrega', 'Pendiente de Entrega'), ('entregada', 'Entregada'), ('cobrada', 'Cobrada'), ('cobrada_parcial', 'Cobrada Parcial'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada')], default='creada', max_length=20),
        ),
    ]
