# Generated by Django 5.0.8 on 2024-10-18 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_alter_statechange_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='customer',
        ),
        migrations.AlterField(
            model_name='return',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='returns', to='sales.sale'),
        ),
    ]
