# Generated by Django 5.0.8 on 2024-10-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_remove_return_customer_alter_return_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collect',
        ),
    ]
