# Generated by Django 5.0.8 on 2024-10-26 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_phone_number'),
        ('products', '0012_alter_product_name'),
        ('sales', '0027_delete_collect'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False if you want to deactivate this record.', verbose_name='active')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing_orders', to='customers.customer')),
            ],
            options={
                'unique_together': {('customer', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='StandingOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False if you want to deactivate this record.', verbose_name='active')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('standing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.standingorder')),
            ],
            options={
                'ordering': ['-created', '-modified', '-is_active'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
