# Generated by Django 5.0.8 on 2024-09-05 21:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertype',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified', '-is_active']},
        ),
        migrations.AddField(
            model_name='usertype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date time on which the object was created.', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to False if you want to deactivate this record.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='usertype',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at'),
        ),
    ]
