# Generated by Django 5.0.8 on 2024-09-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usertype_options_usertype_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SELLER', 'Seller'), ('DELIVERY', 'Delivery')], default='SELLER', max_length=10),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
