# Generated by Django 5.0.8 on 2024-09-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_supplier_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified', '-is_active']},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified', '-is_active']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified', '-is_active']},
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to False if you want to deactivate this record.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to False if you want to deactivate this record.', verbose_name='active'),
        ),
    ]
