# Generated by Django 5.0.8 on 2024-09-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expense_options_alter_expensecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'Expense category', 'verbose_name_plural': 'Expense categories'},
        ),
    ]
