# Generated by Django 5.0.8 on 2024-10-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_alter_supplier_email_alter_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to False if you want to deactivate this record.', verbose_name='active'),
        ),
    ]
