# Generated by Django 5.0.8 on 2024-10-14 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_address_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener el formato: +999999999. Hasta 15 dígitos permitidos.', regex='\\+?1?\\d{9,15}$')]),
        ),
    ]
