# Generated by Django 5.0.8 on 2024-09-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilos')], default='g', max_length=2),
        ),
    ]
