# Generated by Django 5.0.8 on 2024-09-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_weight_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified', '-is_active']},
        ),
        migrations.AlterModelOptions(
            name='productbrand',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified', '-is_active']},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified', '-is_active']},
        ),
        migrations.AddField(
            model_name='productbrand',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to False if you want to deactivate this record.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to False if you want to deactivate this record.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to False if you want to deactivate this record.', verbose_name='active'),
        ),
    ]
