# Generated by Django 5.0.8 on 2024-09-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productbrand_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='product weight'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('g', 'Gramos'), ('kg', 'Kilos')], default='g', max_length=2),
        ),
    ]
