# Generated by Django 5.0.8 on 2024-09-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_weight_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrand',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='brand description'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='name',
            field=models.CharField(max_length=30, verbose_name='brand name'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='category description'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=30, verbose_name='category name'),
        ),
    ]
